import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Define the expected type of props for RootLayout
interface RootLayoutProps {
  children: React.ReactNode;
  params: { locale?: string };
}

export default async function RootLayout({
  children,
  params: { locale }, // Destructure with a default value
}: RootLayoutProps) {
  const messages = await getMessages(); // Pass locale to getMessages if needed

  return (
    <NextIntlClientProvider messages={messages}>
      <html lang={locale}>
        <body className={`antialiased`}>{children}</body>
      </html>
    </NextIntlClientProvider>
  );
}
